### ISSUE TITLE
Sudden crashes

### ISSUE THREAD

**Issue by xyleth** [hobbyquaker/hue2mqtt.js#7]
Hello,

The hue2mqtt code is suddenly crashing at startup with the following error:

hue2mqtt -m mqtt://<MYUSER>:<MYPASS>@<MYSERVER>:1883 -p 5
2018-10-01 10:21:09.160 <info>  hue2mqtt 1.2.0 starting
2018-10-01 10:21:09.201 <info>  mqtt trying to connect mqtt://<MYUSER>:<MYPASS>@<MYSERVER>:1883
2018-10-01 10:21:09.670 <info>  mqtt connected mqtt://<MYUSER>:<MYPASS>@<MYSERVER>:1883
2018-10-01 10:21:09.675 <info>  mqtt subscribe hue/set/#
/usr/lib/node_modules/hue2mqtt/index.js:142
        hue.setGroupLightState(id, state, (err, res) => {
           ^

TypeError: Cannot read property 'setGroupLightState' of undefined
    at setGroupLightState (/usr/lib/node_modules/hue2mqtt/index.js:142:12)
    at MqttClient.mqtt.on.err (/usr/lib/node_modules/hue2mqtt/index.js:120:29)
    at emitThree (events.js:116:13)
    at MqttClient.emit (events.js:194:7)
    at MqttClient._handlePublish (/usr/lib/node_modules/hue2mqtt/node_modules/mqtt/lib/client.js:987:12)
    at MqttClient._handlePacket (/usr/lib/node_modules/hue2mqtt/node_modules/mqtt/lib/client.js:336:12)
    at work (/usr/lib/node_modules/hue2mqtt/node_modules/mqtt/lib/client.js:292:12)
    at Writable.writable._write (/usr/lib/node_modules/hue2mqtt/node_modules/mqtt/lib/client.js:302:5)
    at doWrite (/usr/lib/node_modules/hue2mqtt/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/usr/lib/node_modules/hue2mqtt/node_modules/readable-stream/lib/_stream_writable.js:417:5)

This started happening after a reboot of the raspberry Pi the code runs on.  The reboot was due to a power outage, there were no updates.

I'm running node v6.14.3 on Raspbian Jessie.

Is there anything else I can do to help troubleshoot this?

**Comment by xyleth** [comment]
The issue seemed to be caused by retained messages of light state on the MQTT broker.  Flushing the retained messages db and restarting the broker enabled hue2mqtt to restart normally.  So I suspect some kind of initialisation condition where messages for the hue hub are arriving before the hub object has been created?

Feel free to close if you wish as I've found a workaround to restore function.

**Comment by svrooij** [comment]
@xyleth do we still need to build a fix for this?
